function Y = BWsolver(x,y)

% THi function is an earlier attempt to solve the equation using fsolve.


%Y = zeros(8,1);


        psi = 2;     % assigning the important parameters to variables 
        alpha = 2;   % with names similar to that given in the paper.
        A = 0;
        z = y; 
      
x(1)
sqrt(z)
%Define
theta = [0 :pi/14:pi/2];
%theta6 = [0 :pi/12:pi/2];
%theta5 = [0 :pi/10:pi/2];
eta = z*((sin(theta)).^2);

Y = [x(1) ;
    x(2) - sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-sqrt(z))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2));
    x(3) - x(2) %- sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2)) + ...
    +(sqrt(z)/(2*psi))*((psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2))/(eta(3)-eta(2)) + x(3)*(exp(-A*x(3))))*sin(theta(3))/(1-x(3))+(psi*alpha*(x(2)-sqrt(z))*(exp(-A*x(2)*x(2)/2))/eta(2) ... 
    + x(2)*(exp(-A*x(2))))*(sin(theta(2))/(1-x(2))))*(theta(3)-theta(2));
    
     x(4) - x(3) %- sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2)) + ...
    %+(sqrt(z)/(2*psi))*((psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2)))/(eta(3)-eta(2) + x(3)*exp((-A*x(3))))*sin(theta(3))/(1-x(3))+(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) ... 
    %+ x(2)*(exp(-A*x(2))))*(sin(theta(2))/(1-x(2))))*(theta(3)-theta(2)) 
    + (sqrt(z)/(2*psi))*((psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    + x(4)*(exp(-A*x(4))))*sin(theta(4))+(psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2))/(eta(3)-eta(2)) ...
    + x(3)*(exp(-A*x(3))))*(sin(theta(3))/(1-x(3))))*(theta(4)-theta(3));
    
    x(5) - x(4) %- sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2)) + ...
    %+(sqrt(z)/(2*psi))*((psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2)))/(eta(3)-eta(2) + x(3)*exp((-A*x(3))))*sin(theta(3))/(1-x(3))+(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) ... 
    %+ x(2)*(exp(-A*x(2))))*(sin(theta(2))/(1-x(2))))*(theta(3)-theta(2)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    %+ x(4)*(exp(-A*x(4))))*sin(theta(4))+(psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2))/(eta(3)-eta(2)) ...
    %+ x(3)*(exp(-A*x(3))))*(sin(theta(3))/(1-x(3))))*(theta(4)-theta(3)) 
    + (sqrt(z)/(2*psi))*((psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    + x(5)*(exp(-A*x(5))))*sin(theta(5))+(psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    + x(4)*(exp(-A*x(4))))*(sin(theta(4))/(1-x(4))))*(theta(5)-theta(4));
    
    x(6) - x(5) %- sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2)) + ...
    %+(sqrt(z)/(2*psi))*((psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2)))/(eta(3)-eta(2) + x(3)*exp((-A*x(3))))*sin(theta(3))/(1-x(3))+(psi*alpha*(x(2)-x(1))*(exp(-A*x(2)*x(2)/2))/eta(2) ... 
    %+ x(2)*(exp(-A*x(2))))*(sin(theta(2))/(1-x(2))))*(theta(3)-theta(2)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    %+ x(4)*(exp(-A*x(4))))*sin(theta(4))+(psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2))/(eta(3)-eta(2)) ...
    %+ x(3)*(exp(-A*x(3))))*(sin(theta(3))/(1-x(3))))*(theta(4)-theta(3)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    %+ x(5)*(exp(-A*x(5))))*sin(theta(5))+(psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    %+ x(4)*(exp(-A*x(4))))*(sin(theta(4))/(1-x(4))))*(theta(5)-theta(4))
    + (sqrt(z)/(2*psi))*((psi*alpha*(x(6)-x(5))*(exp(-A*x(6)*x(6)/2))/(eta(6)-eta(5)) ...
    + x(6)*(exp(-A*x(6))))*sin(theta(6))+(psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    + x(5)*(exp(-A*x(5))))*(sin(theta(5))/(1-x(5))))*(theta(6)-theta(5));
    
    x(7) - sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-sqrt(z))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2)) + ...
    +(sqrt(z)/(2*psi))*((psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2)))/(eta(3)-eta(2) + x(3)*exp((-A*x(3))))*sin(theta(3))/(1-x(3))+(psi*alpha*(x(2)-sqrt(z))*(exp(-A*x(2)*x(2)/2))/eta(2) ... 
    + x(2)*(exp(-A*x(2))))*(sin(theta(2))/(1-x(2))))*(theta(3)-theta(2)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    + x(4)*(exp(-A*x(4))))*sin(theta(4))+(psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2))/(eta(3)-eta(2)) ...
    + x(3)*(exp(-A*x(3))))*(sin(theta(3))/(1-x(3))))*(theta(4)-theta(3)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    + x(5)*(exp(-A*x(5))))*sin(theta(5))+(psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    + x(4)*(exp(-A*x(4))))*(sin(theta(4))/(1-x(4))))*(theta(5)-theta(4)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(6)-x(5))*(exp(-A*x(6)*x(6)/2))/(eta(6)-eta(5)) ...
    + x(6)*(exp(-A*x(6))))*sin(theta(6))+(psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    + x(5)*(exp(-A*x(5))))*(sin(theta(5))/(1-x(5))))*(theta(6)-theta(5)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(7)-x(6))*(exp(-A*x(7)*x(7)/2))/(eta(7)-eta(6)) ...
    + x(7)*(exp(-A*x(7))))*sin(theta(7))+(psi*alpha*(x(6)-x(5))*(exp(-A*x(6)*x(6)/2))/(eta(6)-eta(5)) ...
    + x(6)*(exp(-A*x(6))))*(sin(theta(6))/(1-x(6))))*(theta(7)-theta(6));
    
     x(8) - sqrt(z) + (theta(2)*sqrt(z)/(2*psi))*(psi*alpha*(x(2)-sqrt(z))*(exp(-A*x(2)*x(2)/2))/eta(2) + x(2)*(exp(-A*x(2))))*sin(theta(2))/(1-x(2)) + ...
    +(sqrt(z)/(2*psi))*((psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2)))/(eta(3)-eta(2) + x(3)*exp((-A*x(3))))*sin(theta(3))/(1-x(3))+(psi*alpha*(x(2)-sqrt(z))*(exp(-A*x(2)*x(2)/2))/eta(2) ... 
    + x(2)*(exp(-A*x(2))))*(sin(theta(2))/(1-x(2))))*(theta(3)-theta(2)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    + x(4)*(exp(-A*x(4))))*sin(theta(4))+(psi*alpha*(x(3)-x(2))*(exp(-A*x(3)*x(3)/2))/(eta(3)-eta(2)) ...
    + x(3)*(exp(-A*x(3))))*(sin(theta(3))/(1-x(3))))*(theta(4)-theta(3)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    + x(5)*(exp(-A*x(5))))*sin(theta(5))+(psi*alpha*(x(4)-x(3))*(exp(-A*x(4)*x(4)/2))/(eta(4)-eta(3)) ...
    + x(4)*(exp(-A*x(4))))*(sin(theta(4))/(1-x(4))))*(theta(5)-theta(4)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(6)-x(5))*(exp(-A*x(6)*x(6)/2))/(eta(6)-eta(5)) ...
    + x(6)*(exp(-A*x(6))))*sin(theta(6))+(psi*alpha*(x(5)-x(4))*(exp(-A*x(5)*x(5)/2))/(eta(5)-eta(4)) ...
    + x(5)*(exp(-A*x(5))))*(sin(theta(5))/(1-x(5))))*(theta(6)-theta(5)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(7)-x(6))*(exp(-A*x(7)*x(7)/2))/(eta(7)-eta(6)) ...
    + x(7)*(exp(-A*x(7))))*sin(theta(7))+(psi*alpha*(x(6)-x(5))*(exp(-A*x(6)*x(6)/2))/(eta(6)-eta(5)) ...
    + x(6)*(exp(-A*x(6))))*(sin(theta(6))/(1-x(6))))*(theta(7)-theta(6)) + (sqrt(z)/(2*psi))*((psi*alpha*(x(8)-x(7))*(exp(-A*x(8)*x(8)/2))/(eta(8)-eta(7)) ...
    + x(8)*(exp(-A*x(8))))*sin(theta(8))+(psi*alpha*(x(7)-x(6))*(exp(-A*x(7)*x(7)/2))/(eta(7)-eta(6)) ...
    + x(7)*(exp(-A*x(7))))*(sin(theta(7))/(1-x(7))))*(theta(8)-theta(7));];
    
    
